---
title: "FSS"
output:
  html_document: def
---
```{r}
library(hadron)
```

Initializing stuff

```{r echo = FALSE}
rawdata <- "/home/negro/projects/matching/RU1/01_rawdata/OBC/"
plots <- "/home/negro/projects/matching/RU1/02_output/plots/restricted/OBC/"
plots_gen <- "/home/negro/projects/matching/RU1/02_output/plots/general/OBC/"
datas <- "/home/negro/projects/matching/RU1/02_output/data/OBC/"

## set refinement parameters
boot.l <- 500 # block size
boot.R <- 500 # number of bootstrap samples (usually 200, 500 or 1000)
therm <- 500 # number of configuration to discard for thermalization

## set simulation parameters
TT <- c(32) # array of temporal extents to analyse
SS <- c(3, 4, 5, 6, 7, 8, 9, 10) # array of spatial extents to analyse
BB <- c(3) # array of inverse couplings to analyse
R0 <- 0 # starting point (OBC related)

RMAX <- 3 # max length of Wloops

## array of distances (simulation dependent)
r_i <- c()

for(i in seq(1, RMAX - 1)){
  for(j in seq(0, i)){
    value <- sqrt(i^2 + j^2)
    if(value < RMAX)
      r_i <- c(r_i, value)
  }
}

message("r_i: ", paste(r_i, collapse = ", "))
```

Plotting V(r)

```{r}
for (temporal_extent in TT)
{
  for (spatial_extent in SS)
  {
    for (inv_coupling in BB)
    {
      V <- rep(NA, length(r_i))
      bsV <- matrix(NA, nrow = boot.R, ncol = length(r_i))

      folder <- paste0("pascal_OBC_", inv_coupling, "_", spatial_extent, "_", temporal_extent, "_", R0)

      for (rr in seq_along(r_i))
      {
        tmp <- readRDS(paste0(datas, folder, "/fit.result_uncorrelated_", rr, ".rds"))

        V[rr] <- tmp$t0[[2]]
        bsV[, rr] <- tmp$t[, 2]

        pdf(paste0(plots, folder, "/V_r.pdf"))
        plotwitherror(r_i, V, apply(bsV, 2, sd), ylab = "V(r)", xlab = "r", pch = 2, cex = 0.75, main = paste0("V(r) for L = ", spatial_extent, ", beta = ", inv_coupling))
        grid()
        dev.off()
      }
      rm(tmp)
    }
  }
}
```

FSE on r2F.

```{r}
c1 <- "purple"
c2<- "orange"
r123 <- c(1, sqrt(5), sqrt(8))
inv_coupling <- 3
temporal_extent <- 32
SS <- c(3, 4, 5, 6, 7, 8, 9, 10)

indices <- sapply(r123, function(x) which(abs(r_i - x) < 1e-9))

RR <- r_i[indices]

y1_plot <- rep(NA, length(SS))
bsy1_plot <- matrix(NA, nrow = boot.R, ncol = length(SS))
y2_plot <- rep(NA, length(SS))
bsy2_plot <- matrix(NA, nrow = boot.R, ncol = length(SS))

  for (ss in seq_along(SS))
  {
    folder <- paste0("pascal_OBC_", inv_coupling, "_", SS[ss], "_", temporal_extent, "_", R0)

    V <- rep(NA, length(RR))
    bsV <- matrix(NA, nrow = boot.R, ncol = length(RR))

    for (rr in seq_along(RR))
    {
      tmp <- readRDS(paste0(datas, folder, "/fit.result_uncorrelated_", indices[rr], ".rds"))

      V[rr] <- tmp$t0[[2]]
      bsV[, rr] <- tmp$t[, 2]
    }
    rm(tmp)

    g1 <- RR[1] * RR[1] * (V[2] - V[1]) / (RR[2] - RR[1])
    g2 <- RR[2] * RR[2] * (V[3] - V[2]) / (RR[3] - RR[2])

    bsg1 <- RR[1] * RR[1] * (bsV[, 2] - bsV[, 1]) / (RR[2] - RR[1])
    bsg2 <- RR[2] * RR[2] * (bsV[, 3] - bsV[, 2]) / (RR[3] - RR[2])
    rm(V)
    rm(bsV)

    dg1 <- sd(bsg1)
    dg2 <- sd(bsg1)

    y1_plot[ss] <- g1
    bsy1_plot[, ss] <- bsg1
    y2_plot[ss] <- g2
    bsy2_plot[, ss] <- bsg2
  }


pdf(paste0(plots_gen, "FSE/FSE_r2F_", round(RR[1],2), "_", round(RR[2],2), "_", round(RR[3],2) , "_", inv_coupling, ".pdf"))
plotwitherror(SS, y1_plot, apply(bsy1_plot, 2, sd), ylim = c(y1_plot[3], y2_plot[1] + 0.02), col = c1, pch = 2, cex = 1.5, xlab = "L", ylab = "r²F(r, g)")
par(xpd = FALSE)
grid()
par(xpd = TRUE, mar = c(5, 6, 6, 2))

legend(
  x = "top",
  inset = c(0, -0.1),
  bty = "n",
  legend = c(
    expression(g[1]),
    expression(g[2])
  ),
  pch = c(2, 6), # Point types
  pt.cex = 2, # Point sizes
  col = c(c1, c2), # Colors
  y.intersp = 1.5, # Vertical spacing
  ncol = 2
)
legend(
  x = "topright",
  legend = c(expression(r[1] == 1), expression(r[2] == 2.24), expression(r[3] == 2.82), expression("beta" == 3)),
  ncol = 2
)

plotwitherror(SS, y2_plot, apply(bsy2_plot, 2, sd), col = c2, pch = 6, cex = 1.5, xlab = "L", rep = TRUE)

# zooming in top
par(xpd = FALSE, mar = c(5, 6, 6, 2))
plotwitherror(SS, y1_plot, apply(bsy1_plot, 2, sd), col = c1, pch = 2, cex = 1.5, xlab = "L", ylab = expression(g[2]))
grid()

# zooming in bottom
par(xpd = FALSE)
plotwitherror(SS, y2_plot, apply(bsy2_plot, 2, sd), col = c2, pch = 6, cex = 1.5, xlab = "L", ylab = expression(g[1]))
grid()

dev.off()
```

FSE on E0.

```{r}
c1 <- "blue"
c2 <- "red"
c3 <- "green"
r123 <- c(1, sqrt(5), sqrt(8))
inv_coupling <- 3
temporal_extent <- 32
SS <- c(3, 4, 5, 6, 7, 8, 9, 10)

indices <- sapply(r123, function(x) which(abs(r_i - x) < 1e-9))

RR <- r_i[indices]

y1_plot <- rep(NA, length(SS))
bsy1_plot <- matrix(NA, nrow = boot.R, ncol = length(SS))

y2_plot <- rep(NA, length(SS))
bsy2_plot <- matrix(NA, nrow = boot.R, ncol = length(SS))

y3_plot <- rep(NA, length(SS))
bsy3_plot <- matrix(NA, nrow = boot.R, ncol = length(SS))

for (ss in seq_along(SS))
{
  spatial_extent <- SS[ss]

  V <- rep(NA, length(RR))
  bsV <- matrix(NA, nrow = boot.R, ncol = length(RR))

  folder <- paste0("pascal_OBC_", inv_coupling, "_", spatial_extent, "_", temporal_extent, "_", R0)
  
  for (rr in seq_along(RR))
  {
    tmp <- readRDS(paste0(datas, folder, "/fit.result_uncorrelated_", indices[rr], ".rds"))

    V[rr] <- tmp$t0[[2]]
    bsV[, rr] <- tmp$t[, 2]
  }
  rm(tmp)

  y1_plot[ss] <- V[1]
  bsy1_plot[, ss] <- bsV[, 1]
  y2_plot[ss] <- V[2]
  bsy2_plot[, ss] <- bsV[, 2]
  y3_plot[ss] <- V[3]
  bsy3_plot[, ss] <- bsV[, 3]
}

pdf(paste0(plots_gen, "FSE/FSE_E0_", round(RR[1],2), "_", round(RR[2],2), "_", round(RR[3],2) , "_", inv_coupling, ".pdf"))
plotwitherror(SS, y1_plot, apply(bsy1_plot, 2, sd), ylim = c(0.128, 0.275), col = c1, pch = 2, cex = 1.5, ylab = expression(E[0]), xlab = "L")
grid()

par(xpd = TRUE, mar = c(4, 5, 3, 3))
legend(
  x = "topright",
  legend = c(expression(r[1] == 1), expression(r[2] == 2.24), expression(r[3] == 2.82), expression("beta" == 3)),
  ncol = 2
)
legend(
  x = "top",
  inset = c(0, -0.1),
  bty = "n",
  legend = c(
    expression(E[0](r[1])),
    expression(E[0](r[2])),
    expression(E[0](r[3]))
  ),
  pch = c(2, 6, 0), # Point types
  pt.cex = 1.5, # Point sizes
  col = c(c1, c2, c3), # Colors

  y.intersp = 1.5, # Vertical spacing
  ncol = 3
)
plotwitherror(SS, y2_plot, apply(bsy2_plot, 2, sd), col = c2, pch = 6, cex = 1.5, rep = TRUE)
plotwitherror(SS, y3_plot, apply(bsy3_plot, 2, sd), col = c3, pch = 0, cex = 1.5, rep = TRUE)
dev.off()
```
