---
title: "FSS"
output:
  html_document: def
---
```{r}
library(hadron)
```

Initializing stuff

```{r echo = FALSE}
plots <- "/home/negro/projects/matching/RU1/02_output/plots/OBC/"
data <- "/home/negro/projects/matching/RU1/02_output/data/OBC/"
plots_SS <- "/home/negro/projects/matching/RU1/02_output/plots/SS/OBC/"

r_L3 <- c(1, sqrt(2), 2, sqrt(5), sqrt(8))
r_L4 <- c(1, sqrt(2), 2, sqrt(5), sqrt(8), sqrt(10), sqrt(18))
r_L5 <- c(1, sqrt(2), 2, sqrt(5), sqrt(8), sqrt(10), sqrt(18), 5, sqrt(32))

r_L3 <- c(1, sqrt(2), 2, sqrt(5), sqrt(8))
r_L4 <- c(1, sqrt(2), 2, sqrt(5), sqrt(8), sqrt(10), sqrt(18))
r_L5 <- c(1, sqrt(2), 2, sqrt(5), sqrt(8), sqrt(10), sqrt(18), 5, sqrt(32))

r_L6 <- c(1, sqrt(2), sqrt(5), sqrt(8), 3, sqrt(10), sqrt(18), 5, sqrt(32))
r_L7 <- c(1, sqrt(2), sqrt(5), sqrt(8), 3, sqrt(10), sqrt(18), 5, sqrt(32), sqrt(40), sqrt(72))
r_L8 <- c(1, sqrt(2), sqrt(5), sqrt(8), 3, sqrt(10), sqrt(18), 5, sqrt(32), sqrt(40), sqrt(72),  sqrt(45), sqrt(98))


b_L3 <- c(1.4, 1.7, 2, 3, 5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 90, 100)
b_L4 <- c(3.25, 4, 4.25, 4.75, 5, 8, 10, 20, 30, 40, 60, 80)
b_L5 <- c(10, 11, 12, 20, 30, 40, 50, 60, 80, 100)
b_L6 <- c(10)
b_L7 <- c(10)
b_L8 <- c(10)
```

Plotting V(r)

```{r}
temporal_extent <- 32
LL <- c(3, 4, 5, 6, 7, 8)
x0 <- "_0"
boot.R <- 500

for(ll in seq_along(LL))
{
  if(LL[ll] == 3){
    RR <- r_L3
    BB <- b_L3
    spatial_extent <- 3
  }
  else if(LL[ll] == 4){
    RR <- r_L4
    BB <- b_L4
    spatial_extent <- 4
  }
  else if(LL[ll] == 5){
    RR <- r_L5
    BB <- b_L5
    spatial_extent <- 5
  }
  else if(LL[ll] == 6){
    RR <- r_L6
    BB <- b_L6
    spatial_extent <- 6
  }
  else if(LL[ll] == 7){
    RR <- r_L7
    BB <- b_L7
    spatial_extent <- 7
  }
  else if(LL[ll] == 8){
    RR <- r_L8
    BB <- b_L8
    spatial_extent <- 8
  }
  
  V <- rep(NA, length(RR))
  bsV <- matrix(NA, nrow = boot.R, ncol = length(RR))
  
  for(bb in seq_along(BB))
  {
    folder <- paste0("pascal_OBC_", BB[bb], "_", spatial_extent, "_", temporal_extent, x0)
    
    for(rr in seq_along(RR))
    {
      tmp <- readRDS(paste0(data, folder, "/fit.result_correlated_", rr, ".rds"))
      
      V[rr] <- tmp$t0[[2]]
      bsV[,rr] <- tmp$t[,2]
      
      pdf(paste0(plots, folder, "/V_r.pdf"))
      plotwitherror(RR, V, apply(bsV, 2, sd), ylab = "V(r)", xlab = "r", pch = 2, cex = 0.75, main = paste0("V(r) for L = ", spatial_extent, ", beta = ", BB[bb]))
      grid()
      dev.off()
    }
    rm(tmp)
  }
}
```

plotting r2F(r,g) for the same beta ( = 10), at different L, same values of r1 and r2 (r1 = sqrt2 r2 = sqrt5 r3 = sqrt8)

```{r}
temporal_extent <- 32
spatial_extent_array <- c(3, 4, 5, 6, 7, 8)
boot.R = 500
x0 = "_0"

col_array <- c("blue", "red", "orange", "purple", "darkgreen", "magenta")

mask_r_L <- list(c(1, 4, 5), c(1, 4, 5), c(1, 4, 5), c(1, 3, 4), c(1, 3, 4), c(1, 3, 4))
mask_b_L <- list(c(6), c(7), c(1), c(1), c(1), c(1))

x_plot <- rep(NA, length(spatial_extent_array))
y1_plot <- rep(NA, length(spatial_extent_array))
bsy1_plot <- matrix(NA, nrow = boot.R, ncol = length(spatial_extent_array))
y2_plot <- rep(NA, length(spatial_extent_array))
bsy2_plot <- matrix(NA, nrow = boot.R, ncol = length(spatial_extent_array))
 
for(spatial_extent_index in seq_along(spatial_extent_array))
{
  spatial_extent <- spatial_extent_array[spatial_extent_index]
  mask_r <- mask_r_L[[spatial_extent_index]]
  mask_b <- mask_b_L[[spatial_extent_index]]
  
  if(spatial_extent == 3)
  {
    rr <- r_L3[mask_r]
    bb <- b_L3[mask_b]
  }
  else if(spatial_extent == 4)
  {
    rr <- r_L4[mask_r]
    bb <- b_L4[mask_b]
  }
  else if(spatial_extent == 5)
  {
    rr <- r_L5[mask_r]
    bb <- b_L5[mask_b]
  }
  else if(spatial_extent == 6)
  {
    rr <- r_L6[mask_r]
    bb <- b_L6[mask_b]
  }
  else if(spatial_extent == 7)
  {
    rr <- r_L7[mask_r]
    bb <- b_L7[mask_b]
  }
  else if(spatial_extent == 8)
  {
    rr <- r_L8[mask_r]
    bb <- b_L8[mask_b]
  }
  
  V <- rep(NA, length(rr))
  bsV <- matrix(NA, nrow = boot.R, ncol = length(rr))
  g1 <- rep(NA, length(bb))
  bsg1 <- matrix(NA, nrow = boot.R, ncol = length(bb))
  g2 <- rep(NA, length(bb))
  bsg2 <- matrix(NA, nrow = boot.R, ncol = length(bb))
  
  for(i in seq_along(bb))
  {
    folder <- paste0("pascal_OBC_", bb[i], "_", spatial_extent, "_", temporal_extent, x0)
      
    for(j in seq_along(rr))
    {
      tmp <- readRDS(paste0(data, folder, "/fit.result_correlated_", mask_r[j], ".rds"))
      
      V[j] <- tmp$t0[[2]]
      bsV[,j] <- tmp$t[,2]
    }
    rm(tmp)
    
    g1[i] <- rr[1]*rr[1]*(V[2]-V[1])/(rr[2]-rr[1])
    g2[i] <- rr[2]*rr[2]*(V[3]-V[2])/(rr[3]-rr[2])
    
    bsg1[, i] <- rr[1]*rr[1]*(bsV[, 2]-bsV[, 1])/(rr[2] - rr[1])
    bsg2[, i] <- rr[2]*rr[2]*(bsV[, 3]-bsV[, 2])/(rr[3] - rr[2])
  }
  rm(V)
  rm(bsV)
  
  dg1 <- apply(bsg1, 2, sd)
  dg2 <- apply(bsg2, 2, sd)

  x_plot[spatial_extent_index] <- spatial_extent
  y1_plot[spatial_extent_index] <- g1[1]
  bsy1_plot[,spatial_extent_index] <- bsg1[,1]
  y2_plot[spatial_extent_index] <- g2[1]
  bsy2_plot[,spatial_extent_index] <- bsg2[,1]
}

pdf(paste0(plots_SS, "r2F(r,g)_vs_L"))
plotwitherror(x_plot, y1_plot, apply(bsy1_plot, 2, sd), ylim = c(y1_plot[3],y2_plot[1]), col = col_array, pch = 2, cex = 1.5, xlab = "L", ylab = "r²F(r, g)")
par(xpd = FALSE)
grid()
par(xpd=TRUE, mar=c(5, 6, 6, 2))

legend(x = "top",
       inset = c(0, -0.1),
       bty = "n",
       legend = c(expression(g[1]), 
                  expression(g[2])),
       pch = c(2,6),  # Point types
       pt.cex = 2,  # Point sizes
       col = "darkgrey",  # Colors
       y.intersp = 1.5,  # Vertical spacing
       ncol = 2)
legend(x = "topright",
       legend = c(expression(r[1] == 1.4), expression(r[2] == 2.24), expression(r[3] == 2.82), expression("beta" == 10)),
       ncol = 2)

plotwitherror(x_plot, y2_plot, apply(bsy2_plot, 2, sd), col = col_array, pch = 6, cex = 1.5, xlab = "L", rep = TRUE)

#zooming in top
par(xpd = FALSE,  mar=c(5, 6, 6, 2))
plotwitherror(x_plot, y1_plot, apply(bsy1_plot, 2, sd), col = col_array, pch = 2, cex = 1.5, xlab = "L", ylab = expression(g[2]))
grid()

#zooming in bottom
par(xpd = FALSE)
plotwitherror(x_plot, y2_plot, apply(bsy2_plot, 2, sd), col = col_array, pch = 6, cex = 1.5, xlab = "L", ylab = expression(g[1]))
grid()

dev.off()
```
plotting E0(r) for the same beta ( = 10), at different L, same values of r1 and r2 ( r1 = sqrt2 r2 = sqrt5 r3 = sqrt8)

```{r}
temporal_extent <- 32
spatial_extent_array <- c(3, 4, 5, 6, 7, 8)
boot.R = 500
x0 = "_0"

col_array <- c("blue", "red", "orange", "purple", "darkgreen", "magenta")
pch_lst <- list(c(0, 0, 0), c(1, 1, 1), c(2, 2, 2), c(3, 3, 3), c(4, 4, 4), c(5,5,5))
cex_lst <- list(c(1.5, 1.5, 1.5), c(1.5, 1.5, 1.5), c(1.5, 1.5, 1.5), c(1.5, 1.5, 1.5), c(1.5, 1.5, 1.5), c(1.5, 1.5, 1.5))

mask_r_L <- list(c(1, 4, 5), c(1, 4, 5), c(1, 4, 5), c(1, 3, 4), c(1,3,4), c(1,3,4))
mask_b_L <- list(c(6), c(7), c(1), c(1), c(1), c(1))

x_plot <- rep(NA, length(spatial_extent_array))

y1_plot <- rep(NA, length(spatial_extent_array))
bsy1_plot <- matrix(NA, nrow = boot.R, ncol = length(spatial_extent_array))

y2_plot <- rep(NA, length(spatial_extent_array))
bsy2_plot <- matrix(NA, nrow = boot.R, ncol = length(spatial_extent_array))

y3_plot <- rep(NA, length(spatial_extent_array))
bsy3_plot <- matrix(NA, nrow = boot.R, ncol = length(spatial_extent_array))
 
for(spatial_extent_index in seq_along(spatial_extent_array))
{
  spatial_extent <- spatial_extent_array[spatial_extent_index]
  mask_r <- mask_r_L[[spatial_extent_index]]
  mask_b <- mask_b_L[[spatial_extent_index]]
  
  if(spatial_extent == 3)
  {
    rr <- r_L3[mask_r]
    bb <- b_L3[mask_b]
  }
  else if(spatial_extent == 4)
  {
    rr <- r_L4[mask_r]
    bb <- b_L4[mask_b]
  }
  else if(spatial_extent == 5)
  {
    rr <- r_L5[mask_r]
    bb <- b_L5[mask_b]
  }
  else if(spatial_extent == 6)
  {
    rr <- r_L6[mask_r]
    bb <- b_L6[mask_b]
  }
  
  V <- rep(NA, length(rr))
  bsV <- matrix(NA, nrow = boot.R, ncol = length(rr))
  
  for(i in seq_along(bb))
  {
    folder <- paste0("pascal_OBC_", bb[i], "_", spatial_extent, "_", temporal_extent, x0)
      
    for(j in seq_along(rr))
    {
      tmp <- readRDS(paste0(data, folder, "/fit.result_correlated_", mask_r[j], ".rds"))
      
      V[j] <- tmp$t0[[2]]
      bsV[,j] <- tmp$t[,2]
    }
    rm(tmp)
  }
  
  col <- col_array[spatial_extent_index]
  pch <- pch_lst[[spatial_extent_index]]
  cex <- cex_lst[[spatial_extent_index]]

  x_plot[spatial_extent_index] <- spatial_extent
  y1_plot[spatial_extent_index] <- V[1]
  bsy1_plot[,spatial_extent_index] <- bsV[,1]
  y2_plot[spatial_extent_index] <- V[2]
  bsy2_plot[,spatial_extent_index] <- bsV[,2]
  y3_plot[spatial_extent_index] <- V[3]
  bsy3_plot[,spatial_extent_index] <- bsV[,3]
}

pdf(paste0(plots_SS, "E0_vs_L.pdf"))
plotwitherror(x_plot, y1_plot, apply(bsy1_plot, 2, sd), ylim = c(0.035,0.074), col = col_array, pch = 2, cex = 1.5, ylab = expression(E[0]), xlab = "L")
grid()

par(xpd=TRUE, mar=c(4, 5, 3, 3))
legend(x = "topright",
       legend = c(expression(r[1] == 1.4), expression(r[2] == 2.24), expression(r[3] == 2.82), expression("beta" == 10)),
       ncol = 2)
legend(x = "top",
       inset = c(0, -0.1),
       bty = "n",
       legend = c(expression(E[0](r[1])),
                  expression(E[0](r[2])),
                  expression(E[0](r[3]))),
       pch = c(2, 6, 0),  # Point types
       pt.cex = 1.5,  # Point sizes
       col = c("darkgrey"),  # Colors
       
       y.intersp = 1.5,  # Vertical spacing
       ncol = 3)
plotwitherror(x_plot, y2_plot, apply(bsy2_plot, 2, sd), col = col_array, pch = 6, cex = 1.5, rep = TRUE)
plotwitherror(x_plot, y3_plot, apply(bsy3_plot, 2, sd), col = col_array, pch = 0, cex = 1.5, rep = TRUE)
dev.off()

```
