---
title: "E0 and r2F for non linear Wilson loop, beta = 4, linear fit function, r = 1, sqrt(2)."
output: html_document
---
Here are the parameters being used

```{r}
# load libraries
library(hadron)
library(latex2exp)

# import functions
source("~/projects/stepscaling/RU1/03_functions/myFunctions.R")

# set parameters
spatialExtent <- c(3, 4, 5, 6, 7, 8)
temporalExtent <- 32

invCoupling <- 4

bootSamples <- 1000

extra <- c(0, 0, 0, 0, 0, 0)

flag <- "backprop"

rsq <- c(1, 2, 4)

fn <- function (par, x, boot.r, ...) par[1] * log(par[2] * x)
```

Computing r2F

```{r echo = FALSE}
g1Lst <- list()
g2Lst <- list()

VLst <- list()

for (i in seq_along(spatialExtent)){
  source("~/projects/stepscaling/RU1/03_functions/myFunctions.R")
  
  extra_val <- extra[i]
  spatialExtent_val <- spatialExtent[i]
  
  betaPrecision <- sprintf("%.6f", invCoupling)

  inputFileName <- inputFileName(spatialExtent_val
                                   , temporalExtent
                                   , invCoupling
                                   , extra = extra_val)
  dataFile <- dataFileNP(spatialExtent_val
                         , temporalExtent
                         , betaPrecision)
  
  dataPath <- dataPath(inputFileName)
  plotPath <- plotPath(inputFileName)
  writePath <- writePath(inputFileName)
  
  cat("results for L T beta",spatialExtent_val, temporalExtent, invCoupling, "\n" )
  
  V <- rep(NA, length(rsq))
  bsV <- matrix(NA, nrow = bootSamples, ncol = length(rsq))
  
  for(j in seq_along(rsq)){
    tmp <- readRDS(paste0(writePath, "wrtFitResults_rsq_", rsq[j],"_", flag, ".rds"))
    V[j] <- tmp$t0[[2]]
    bsV[,j] <- tmp$t[,2]
  }
  
  g1 <- rsq[1]*(V[2]-V[1])/(sqrt(rsq[2])-sqrt(rsq[1]))
  g2 <- rsq[2]*(V[3]-V[2])/(sqrt(rsq[3])-sqrt(rsq[2]))
  
  bsg1 <- rsq[1]*(bsV[,2]-bsV[,1])/(sqrt(rsq[2])-sqrt(rsq[1]))
  bsg2 <- rsq[2]*(bsV[,3]-bsV[,2])/(sqrt(rsq[3])-sqrt(rsq[2]))
  
  sublist <- list(V, bsV)
  VLst[[i]] <- sublist
  
  sublist <- list(g1, bsg1)
  g1Lst[[i]] <- sublist 
  
  sublist <- list(g2, bsg2)
  g2Lst[[i]] <- sublist
}
rm(sublist)
rm(tmp)
```

Here is a plot of the ground state energy for r = 1

```{r echo = FALSE}
x <- spatialExtent

value <- rep(NA, length(x))

boot.R <- bootSamples

bsamples <- matrix(NA, nrow = boot.R, ncol = length(x))

for(i in seq_along(x)){
  value[i] <- VLst[[i]][[1]][1]
  bsamples[,i] <- VLst[[i]][[2]][,1]
}

plotwitherror(x, value, sd(bsamples), main = paste0("E_0 for r² = ", rsq[1], " beta = ", invCoupling), xlab = "L/a", ylab = "E_0")

# fit.result <- bootstrap.nlsfit(fn, c(1,1,1), value, x, bsamples)
# summary(fit.result)
# plot(fit.result, main = paste0("E_0 for r² = ", rsq[1], " beta = ", invCoupling), xlab = "L/a", ylab = "E_0")
```

Here is a plot of the ground state energy for r = sqrt(2)

```{r echo = FALSE}
x <- spatialExtent

value <- rep(NA, length(x))

boot.R <- bootSamples

bsamples <- matrix(NA, nrow = boot.R, ncol = length(x))

for(i in seq_along(x)){
  value[i] <- VLst[[i]][[1]][2]
  bsamples[,i] <- VLst[[i]][[2]][,2]
}

plotwitherror(x, value, dy = sd(bsamples, na.rm = TRUE), main = paste0("E_0 for r² = ", rsq[2], " beta = ", invCoupling), xlab = "L/a", ylab = "E_0")

# fit.result <- bootstrap.nlsfit(fn, c(1,1,1), value, x, bsamples)
# summary(fit.result)
# plot(fit.result, main = paste0("E_0 for r² = ", rsq[2], " beta = ", invCoupling), xlab = "L/a", ylab = "E_0")
```

Here is a plot of the ground state energy for r = 2

```{r echo = FALSE}
x <- spatialExtent

value <- rep(NA, length(x))

boot.R <- bootSamples

bsamples <- matrix(NA, nrow = boot.R, ncol = length(x))

for(i in seq_along(x)){
  value[i] <- VLst[[i]][[1]][3]
  bsamples[,i] <- VLst[[i]][[2]][,3]
}

plotwitherror(x, value, dy = sd(bsamples, na.rm = TRUE), main = paste0("E_0 for r² = ", rsq[3], " beta = ", invCoupling), xlab = "L/a", ylab = "E_0")

# fit.result <- bootstrap.nlsfit(fn, c(1,1), value, x, bsamples)
# summary(fit.result)
# plot(fit.result, main = paste0("E_0 for r² = ", rsq[3], " beta = ", invCoupling), xlab = "L/a", ylab = "E_0")
```

Here is a plot of the running coupling r^2F(r,g) for r = 1

```{r echo = FALSE}
x <- spatialExtent

value <- rep(NA, length(x))

boot.R <- bootSamples

bsamples <- matrix(NA, nrow = boot.R, ncol = length(x))

for(i in seq_along(x)){
  value[i] <- g1Lst[[i]][1]
  bsamples[,i] <- unlist(g1Lst[[i]][2])
}

value <- unlist(value)
bsamples <- as.matrix(bsamples, nrow = boot.R, ncol = length(x))

plotwitherror(x, value, dy = sd(bsamples, na.rm = TRUE), main = paste0("r2F(r,beta) for r² = ", rsq[1], " beta =", invCoupling), xlab = "L/a", ylab = "r2F")

# fit.result <- bootstrap.nlsfit(fn, c(0.3,1), value, x, bsamples)
# summary(fit.result)
# plot(fit.result, main = paste0("r2F(r,beta) for r² = ", rsq[1], " beta =", invCoupling), xlab = "L/a", ylab = "r2F")
```

Here is a plot of the running coupling r^2F(r,g) for r = sqrt(2)

```{r}
x <- spatialExtent

value <- rep(NA, length(x))

boot.R <- bootSamples

bsamples <- matrix(NA, nrow = boot.R, ncol = length(x))

for(i in seq_along(x)){
  value[i] <- g2Lst[[i]][1]
  bsamples[,i] <- unlist(g2Lst[[i]][2])
}

value <- unlist(value)
bsamples <- as.matrix(bsamples, nrow = boot.R, ncol = length(x))

plotwitherror(x, value, dy = sd(bsamples, na.rm = TRUE), main = paste0("r2F(r,beta) for r² = ", rsq[2], " beta =", invCoupling), xlab = "L/a", ylab = "r2F")
 
# fit.result <- bootstrap.nlsfit(fn, c(0.3,1), value, x, bsamples)
# summary(fit.result)
# plot(fit.result, main = paste0("r2F(r,beta) for r² = ", rsq[2], " beta =", invCoupling), xlab = "L/a", ylab = "r2F")
```
```{r echo = FALSE}
# rmarkdown::render("/home/negro/projects/stepscaling/RU1/04_scripts/10_E0_r2F_visualization_fit.Rmd", output_file = paste0("/home/negro/projects/stepscaling/RU1/02_output/plots/stepScalingPlots/", flag,"_E0_r2F_b", invCoupling,"_rsq", rsq[1],"_" ,rsq[2],".html"))

```

