---
title: "analysis of non planar Wilson loops, klft output."
output:
  html_document: def
---
Loading parameters and libraries.

```{r}
library(hadron)
```

Initial parameters

```{r}
boot.l = 500
boot.R = 500
therm = 500

temporal_extent <- 32
spatial_extent <- 7
inv_coupling <- 10

if(spatial_extent == 3)
  r_i <- c(1, sqrt(2), 2, sqrt(5), sqrt(8))
if(spatial_extent == 4)
  r_i <- c(1, sqrt(2), 2, sqrt(5), sqrt(8), sqrt(10), sqrt(18))
if(spatial_extent == 5)
  r_i <- c(1, sqrt(2), 2, sqrt(5), sqrt(8), sqrt(10), sqrt(18), 5, sqrt(32))
if(spatial_extent == 6) ##changed in the script
  r_i <- c(1, sqrt(2), sqrt(5), sqrt(8), 3, sqrt(10), sqrt(18), 5, sqrt(32))
if(spatial_extent == 7) ##changed in the script
  r_i <- c(1, sqrt(2), sqrt(5), sqrt(8), 3, sqrt(10), sqrt(18), 5, sqrt(32), sqrt(40), sqrt(72))
if(spatial_extent == 8) ##changed in the script
  r_i <- c(1, sqrt(2), sqrt(5), sqrt(8), 3, sqrt(10), sqrt(18), 5, sqrt(32), sqrt(40), sqrt(72), sqrt(45), sqrt(98))

extra = "_0"

folder <- paste0("pascal_OBC_", inv_coupling, "_", spatial_extent, "_", temporal_extent, extra)

rawdata <- "/home/negro/projects/matching/RU1/01_rawdata/OBC/"
plots <- "/home/negro/projects/matching/RU1/02_output/plots/OBC/"
datas <- "/home/negro/projects/matching/RU1/02_output/data/OBC/"

dir.create(paste0(plots, folder))
dir.create(paste0(datas, folder))
```

Extracting data into matrix

```{r}
data <- as.matrix(read.table(paste0(rawdata, folder, "/", folder, ".dat"), skip = 1))
```

MCMC history

```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
pdf(paste0(plots, folder, "/thermalization.pdf"))
for(i in seq_along(r_i)){
  W <- data[, seq(4 + i, ncol(data), length(r_i))]
  time_series <- W[, 1]
  plot(x = c(1:length(time_series)), y = time_series, xlab = "n_configs", ylab = "W(R,T)", main = paste0("W(R,T) for T = 1, R = ", r_i[i]))

  plot(computeacf(time_series), main = paste0("Autocorrelation function W(R,T) for T = 1, R = ", r_i[i]))
  #summary(myacf)
  #cat("\n")
  rm(W)
  rm(time_series)
}
dev.off()
rm(data)
```
Bootstrap analysis

```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
data <- as.matrix(read.table(paste0(rawdata, folder, "/", folder, ".dat"), skip = 1 + therm))

pdf(paste0(plots, folder, "/bootstrap_analysis.pdf"))
for(i in seq_along(r_i)){
  tmp <- data[, seq(5 + (i-1) , ncol(data), length(r_i))]
  Time <- ncol(tmp)
  
  tmp <- cf_orig(cf = tmp)
  tmp <- cf_meta(tmp, nrObs = 1, Time = Time)
  
  bootstrap.analysis(tmp$cf[, 1], boot.R = boot.R, boot.l = 2, pl = TRUE)
  rm(tmp)
}
dev.off()
```

Bootstrapping data

```{r}
W <- list()

for(i in seq_along(r_i)){
  tmp <- data[, seq(5 + (i-1), ncol(data), length(r_i))]
  Time <- ncol(tmp)

  tmp <- cf_orig(cf = tmp)
  tmp <- cf_meta(tmp, nrObs = 1, nrStypes = 0, Time = Time)
  
  W[[length(W) + 1]] <- bootstrap.cf(cf = tmp, boot.R = boot.R, boot.l = boot.l, sim = "fixed", endcorr = TRUE, seed = 1234567)
}

saveRDS(W, paste0(datas, folder, "/Wloops.rds"))
```

Plotting data

```{r}
pdf(paste0(plots, folder, "/NPWL.pdf"))
for(i in seq_along(r_i)){
  plot(W[[i]], main = paste0("Non planar Wilson loop for R = ", r_i[i]), ylab = "W(R,T)", xlab = "t")
  grid()
  plot(W[[i]], log = "y", main = paste0("Non planar Wilson loop for R = ", r_i[i], ", logscale"), ylab = "W(R,T)", xlab = "t")
  grid()
}
```

Effective mass

```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
if(!exists("W"))
{
  W <- readRDS(paste0(datas, folder, "/Wloops.rds"))
}
pdf(paste0(plots, folder, "/EMASS.pdf"))

lims1 <- rep(list(c(0, 0.1)), length(r_i)%/%2)
lims2 <- rep(list(c(0, 0.2)), length(r_i)%/%2+1)
lims <- c(lims1, lims2)

#lims <- list(c(0.035, 0.042), c(0.04, 0.06), c(0.05, 0.07), c(0.05, 0.07), c(0.06, 0.08), c(0.065, 0.085), c(0.085, 0.12))

for(i in seq_along(r_i)){
  e_mass <- bootstrap.effectivemass(W[[i]], type = "log")
  plot(e_mass, main = paste0("Effectiva mass for r = ", r_i[i]), ylab = expression(m[eff]), xlab = "t", xlim = c(0,24), ylim = lims[[i]])
  grid()
}

dev.off()
```
Fit stuff

```{r}
if(!exists("W")){
W <- readRDS(paste0(datas, folder, "/Wloops.rds"))
}
range <- seq(1,temporal_extent-1) #????

mask <- list(seq(6,16), seq(6,16),seq(6,16),seq(6,16),seq(6,16),seq(6,16),seq(6,16),seq(6,16),seq(6,16),seq(6,16),seq(6,16), seq(6,16), seq(6,16), seq(6,16), seq(6,16))

fn <- function(par, x, boot.r, ...) par[1] * exp(-par[2] * x)
```

Fit routine uncorrelated data

```{r}
pdf(paste0(plots, folder, "/uncorrelated_fit.pdf"))

for(i in seq_along(r_i)){
  value <- W[[i]]$cf.tsboot$t0
  bsamples <- W[[i]]$cf.tsboot$t

  fit.result_uncorrelated <- bootstrap.nlsfit(fn = fn, par.guess = c(0.05, 0.02), y = value, x = range, bsamples = bsamples, mask = mask[[i]], use.minpack.lm = FALSE)

  plot(fit.result_uncorrelated, main = paste0("Fit with a*exp(-E_0*t) with r = ", r_i[i]), ylab = "W(R,T)", xlab = "t", xlim = c(mask[[i]][1], mask[[i]][length(mask[[i]])]), ylim =rev(c(value[mask[[i]][1]], value[mask[[i]][length(mask[[i]])]])), log = "y")
  legend(x = "topright", legend = c(paste0("chi2 = ", round(fit.result_uncorrelated$chisqr,2)), paste0("dof = ", fit.result_uncorrelated$dof), paste0("a = ", round(fit.result_uncorrelated$t0[1], 5)), paste0("da = ", round(fit.result_uncorrelated$se[1], 5)), paste0("E_0 = ", round(fit.result_uncorrelated$t0[2], 5)), paste0("dE_0 = ", round(fit.result_uncorrelated$se[2], 5))))
  
    plot(fit.result_uncorrelated, main = paste0("Fit with a*exp(-E_0*t) with r = ", r_i[i]), ylab = "W(R,T)", xlab = "t", log = "y")
  legend(x = "topright", legend = c(paste0("chi2 = ", round(fit.result_uncorrelated$chisqr,2)), paste0("dof = ", fit.result_uncorrelated$dof), paste0("a = ", round(fit.result_uncorrelated$t0[1], 5)), paste0("da = ", round(fit.result_uncorrelated$se[1],5)), paste0("E_0 = ", round(fit.result_uncorrelated$t0[2], 5)), paste0("dE_0 = ", round(fit.result_uncorrelated$se[2], 5))))
  
  dof <- fit.result_uncorrelated$dof
  chi2 <- fit.result_uncorrelated$chisqr
  
  print(paste0("R = ", r_i[i]))
  print("result")
  print(fit.result_uncorrelated$t0)
  print("error")
  print(fit.result_uncorrelated$se)
  print("chi2/dof")
  print(chi2/dof)
  cat("\n")
  
  saveRDS(fit.result_uncorrelated, paste0(datas, folder, "/fit.result_uncorrelated_", i,".rds"))
}
dev.off()
```
Fit routine correlated

```{r}
pdf(paste0(plots, folder, "/correlated_fit.pdf"))
for(i in seq_along(r_i)){
  value <- W[[i]]$cf.tsboot$t0
  bsamples <- W[[i]]$cf.tsboot$t
  
  fit.result_correlated <- bootstrap.nlsfit(fn = fn, par.guess = c(0.05, 0.02), y = value, x = range, bsamples = bsamples, mask = mask[[i]], use.minpack.lm = FALSE, CovMatrix = NULL)
  
    plot(fit.result_correlated, main = paste0("Fit with a*exp(-E_0*t) with r = ", r_i[i]), ylab = "W(R,T)", xlab = "t", xlim = c(0,32), log = "y")
  legend(x = "topright", legend = c(paste0("chi2 = ", round(fit.result_correlated$chisqr,2)), paste0("dof = ", fit.result_correlated$dof), paste0("a = ", round(fit.result_correlated$t0[1], 5)), paste0("da = ", round(fit.result_correlated$se[1],5)), paste0("E_0 = ", round(fit.result_correlated$t0[2], 5)), paste0("dE_0 = ", round(fit.result_correlated$se[2], 5))))
  
  dof <- fit.result_correlated$dof
  chi2 <- fit.result_correlated$chisqr
  
  print(paste0("R = ", r_i[i]))
  print("result")
  print(fit.result_correlated$t0)
  print("error")
  print(fit.result_correlated$se)
  print("chi2/dof")
  print(chi2/dof)
  cat("\n")
  
  saveRDS(fit.result_correlated, paste0(datas, folder, "/fit.result_correlated_", i,".rds"))
}
dev.off()
```
```{r}
rm(list = ls())
```



